// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package postgresgen

import (
	"context"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
    id,
    issue_id,
    project_id,
    event_id,
    platform,
    environment,
    release,
    level,
    title,
    culprit,
    exception_type,
    exception_value,
    fingerprint,
    payload,
    received_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
`

type CreateEventParams struct {
	ID             string
	IssueID        string
	ProjectID      string
	EventID        string
	Platform       string
	Environment    string
	Release        string
	Level          string
	Title          string
	Culprit        string
	ExceptionType  string
	ExceptionValue string
	Fingerprint    string
	Payload        string
	ReceivedAt     int64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.ID,
		arg.IssueID,
		arg.ProjectID,
		arg.EventID,
		arg.Platform,
		arg.Environment,
		arg.Release,
		arg.Level,
		arg.Title,
		arg.Culprit,
		arg.ExceptionType,
		arg.ExceptionValue,
		arg.Fingerprint,
		arg.Payload,
		arg.ReceivedAt,
	)
	return err
}

const createIssue = `-- name: CreateIssue :exec
INSERT INTO issues (
    id,
    project_id,
    grouping_key,
    title,
    culprit,
    platform,
    environment,
    level,
    status,
    first_seen_at,
    last_seen_at,
    event_count,
    last_event_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
`

type CreateIssueParams struct {
	ID          string
	ProjectID   string
	GroupingKey string
	Title       string
	Culprit     string
	Platform    string
	Environment string
	Level       string
	Status      string
	FirstSeenAt int64
	LastSeenAt  int64
	EventCount  int64
	LastEventID string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) error {
	_, err := q.db.ExecContext(ctx, createIssue,
		arg.ID,
		arg.ProjectID,
		arg.GroupingKey,
		arg.Title,
		arg.Culprit,
		arg.Platform,
		arg.Environment,
		arg.Level,
		arg.Status,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.EventCount,
		arg.LastEventID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
    id,
    slug,
    name,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateOrganizationParams struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (
    id,
    organization_id,
    slug,
    name,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateProjectParams struct {
	ID             string
	OrganizationID string
	Slug           string
	Name           string
	CreatedAt      int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createProjectKey = `-- name: CreateProjectKey :exec
INSERT INTO project_keys (
    id,
    project_id,
    public_key,
    secret_key,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateProjectKeyParams struct {
	ID        string
	ProjectID string
	PublicKey string
	SecretKey string
	CreatedAt int64
}

func (q *Queries) CreateProjectKey(ctx context.Context, arg CreateProjectKeyParams) error {
	_, err := q.db.ExecContext(ctx, createProjectKey,
		arg.ID,
		arg.ProjectID,
		arg.PublicKey,
		arg.SecretKey,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id,
    user_id,
    token_hash,
    created_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    email,
    password_hash,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getEventByProjectAndEventID = `-- name: GetEventByProjectAndEventID :one
SELECT
    id,
    issue_id,
    project_id,
    event_id,
    platform,
    environment,
    level,
    title,
    culprit,
    exception_type,
    exception_value,
    fingerprint,
    payload,
    received_at
FROM events
WHERE project_id = $1
  AND event_id = $2
LIMIT 1
`

type GetEventByProjectAndEventIDParams struct {
	ProjectID string
	EventID   string
}

func (q *Queries) GetEventByProjectAndEventID(ctx context.Context, arg GetEventByProjectAndEventIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByProjectAndEventID, arg.ProjectID, arg.EventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ProjectID,
		&i.EventID,
		&i.Platform,
		&i.Environment,
		&i.Level,
		&i.Title,
		&i.Culprit,
		&i.ExceptionType,
		&i.ExceptionValue,
		&i.Fingerprint,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const getIssueByGroupingKey = `-- name: GetIssueByGroupingKey :one
SELECT
    id,
    project_id,
    grouping_key,
    title,
    culprit,
    platform,
    environment,
    status,
    first_seen_at,
    last_seen_at,
    event_count,
    last_event_id,
    created_at,
    updated_at
FROM issues
WHERE project_id = $1
  AND grouping_key = $2
LIMIT 1
`

type GetIssueByGroupingKeyParams struct {
	ProjectID   string
	GroupingKey string
}

func (q *Queries) GetIssueByGroupingKey(ctx context.Context, arg GetIssueByGroupingKeyParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByGroupingKey, arg.ProjectID, arg.GroupingKey)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GroupingKey,
		&i.Title,
		&i.Culprit,
		&i.Platform,
		&i.Environment,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.EventCount,
		&i.LastEventID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT
    i.id,
    i.project_id,
    p.name AS project_name,
    i.grouping_key,
    i.title,
    i.culprit,
    i.platform,
    i.environment,
    i.status,
    i.first_seen_at,
    i.last_seen_at,
    i.event_count,
    i.last_event_id
FROM issues AS i
JOIN projects AS p ON p.id = i.project_id
WHERE i.id = $1
LIMIT 1
`

type GetIssueByIDRow struct {
	ID          string
	ProjectID   string
	ProjectName string
	GroupingKey string
	Title       string
	Culprit     string
	Platform    string
	Environment string
	Status      string
	FirstSeenAt int64
	LastSeenAt  int64
	EventCount  int64
	LastEventID string
}

func (q *Queries) GetIssueByID(ctx context.Context, id string) (GetIssueByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i GetIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectName,
		&i.GroupingKey,
		&i.Title,
		&i.Culprit,
		&i.Platform,
		&i.Environment,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.EventCount,
		&i.LastEventID,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, slug, name, created_at
FROM projects
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectKeyByPublicKey = `-- name: GetProjectKeyByPublicKey :one
SELECT
    pk.id,
    pk.project_id,
    pk.public_key,
    pk.secret_key,
    pk.created_at,
    p.name AS project_name
FROM project_keys AS pk
JOIN projects AS p ON p.id = pk.project_id
WHERE pk.project_id = $1
  AND pk.public_key = $2
LIMIT 1
`

type GetProjectKeyByPublicKeyParams struct {
	ProjectID string
	PublicKey string
}

type GetProjectKeyByPublicKeyRow struct {
	ID          string
	ProjectID   string
	PublicKey   string
	SecretKey   string
	CreatedAt   int64
	ProjectName string
}

func (q *Queries) GetProjectKeyByPublicKey(ctx context.Context, arg GetProjectKeyByPublicKeyParams) (GetProjectKeyByPublicKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectKeyByPublicKey, arg.ProjectID, arg.PublicKey)
	var i GetProjectKeyByPublicKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PublicKey,
		&i.SecretKey,
		&i.CreatedAt,
		&i.ProjectName,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id,
    s.user_id,
    s.token_hash,
    s.created_at,
    s.expires_at,
    u.email
FROM sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE s.token_hash = $1
LIMIT 1
`

type GetSessionByTokenHashRow struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedAt int64
	ExpiresAt int64
	Email     string
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByIssue = `-- name: ListEventsByIssue :many
SELECT
    id,
    issue_id,
    project_id,
    event_id,
    platform,
    environment,
    release,
    level,
    title,
    culprit,
    exception_type,
    exception_value,
    fingerprint,
    payload,
    received_at
FROM events
WHERE issue_id = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListEventsByIssueParams struct {
	IssueID    string
	LimitCount int32
}

func (q *Queries) ListEventsByIssue(ctx context.Context, arg ListEventsByIssueParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByIssue, arg.IssueID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ProjectID,
			&i.EventID,
			&i.Platform,
			&i.Environment,
			&i.Release,
			&i.Level,
			&i.Title,
			&i.Culprit,
			&i.ExceptionType,
			&i.ExceptionValue,
			&i.Fingerprint,
			&i.Payload,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT
    i.id,
    i.project_id,
    p.name AS project_name,
    i.title,
    i.culprit,
    i.platform,
    i.environment,
    i.status,
    i.first_seen_at,
    i.last_seen_at,
    i.event_count,
    i.last_event_id
FROM issues AS i
JOIN projects AS p ON p.id = i.project_id
ORDER BY i.last_seen_at DESC
LIMIT $1
`

type ListIssuesRow struct {
	ID          string
	ProjectID   string
	ProjectName string
	Title       string
	Culprit     string
	Platform    string
	Environment string
	Status      string
	FirstSeenAt int64
	LastSeenAt  int64
	EventCount  int64
	LastEventID string
}

func (q *Queries) ListIssues(ctx context.Context, limitCount int32) ([]ListIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssues, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesRow
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Title,
			&i.Culprit,
			&i.Platform,
			&i.Environment,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.EventCount,
			&i.LastEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueAfterEvent = `-- name: UpdateIssueAfterEvent :exec
UPDATE issues
SET
    title = $1,
    culprit = $2,
    platform = $3,
    environment = $4,
    level = $5,
    last_seen_at = $6,
    event_count = $7,
    last_event_id = $8,
    updated_at = $9,
    status = CASE WHEN status = 'resolved' THEN 'open' ELSE status END
WHERE id = $10
`

type UpdateIssueAfterEventParams struct {
	Title       string
	Culprit     string
	Platform    string
	Environment string
	Level       string
	LastSeenAt  int64
	EventCount  int64
	LastEventID string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateIssueAfterEvent(ctx context.Context, arg UpdateIssueAfterEventParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueAfterEvent,
		arg.Title,
		arg.Culprit,
		arg.Platform,
		arg.Environment,
		arg.Level,
		arg.LastSeenAt,
		arg.EventCount,
		arg.LastEventID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateIssueStatusParams struct {
	Status    string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
