// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlitegen

type Event struct {
	ID             string
	IssueID        string
	ProjectID      string
	EventID        string
	Platform       string
	Environment    string
	Release        string
	Level          string
	Title          string
	Culprit        string
	ExceptionType  string
	ExceptionValue string
	Fingerprint    string
	Payload        string
	ReceivedAt     int64
}

type Issue struct {
	ID          string
	ProjectID   string
	GroupingKey string
	Title       string
	Culprit     string
	Platform    string
	Environment string
	Status      string
	FirstSeenAt int64
	LastSeenAt  int64
	EventCount  int64
	LastEventID string
	CreatedAt   int64
	UpdatedAt   int64
}

type Organization struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt int64
}

type Project struct {
	ID             string
	OrganizationID string
	Slug           string
	Name           string
	CreatedAt      int64
}

type ProjectKey struct {
	ID        string
	ProjectID string
	PublicKey string
	SecretKey string
	CreatedAt int64
}

type Session struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedAt int64
	ExpiresAt int64
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    int64
}
